# coding: utf-8
title: 넷평 남짓한 공간
url: http://netpyoung.github.io
description: netpyoung's blog

author :
    name : Eunpyoung Kim
    email : netpyoung@gmail.com
    github : https://github.com/netpyoung
    facebook : https://www.facebook.com/netpyoung
    flickr : https://www.flickr.com/photos/netpyoung
    youtube : https://www.youtube.com/user/netpyoung/videos


include: ["/blog", "/external", "/diary", "/res"]
exclude: ["README.md", 'Rakefile']

Paths :
    home: /
    blog: /blog
    resume: /resume
    external: /external
    diary: /diary
    resources: /res
    feed: /feed

# ref: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:title

#markdown: kramdown
#kramdown:
#    input: GFM

# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
