title: 넷평 남짓한 공간
url: http://netpyoung.github.io
description: netpyoung's blog

author :
    name : Eunpyoung Kim
    email : netpyoung@gmail.com
    github : netpyoung
    facebook : netpyoung


include: ["/blog", "/external"]
exclude: ["README.md"]

Paths :
    home: /
    blog: /blog
    external: /external
    resources: /res
	diary: /diary
    feed: /feed

# ref: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:title

pygments: true

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
