# coding: utf-8
title: 넷평 남짓한 공간
url: http://netpyoung.github.io
description: netpyoung's blog

author :
    name : Eunpyoung Kim
    email : netpyoung@gmail.com
    github : https://github.com/netpyoung
    facebook : https://www.facebook.com/netpyoung
    flickr : https://www.flickr.com/photos/netpyoung
    youtube : https://www.youtube.com/user/netpyoung/videos


include: ["/sitemap", "/res"]
exclude: ["README.md"]

Paths :
    home: /
    blog: /blog
    resume: /resume
    external: /external
    diary: /diary
    resources: /res
    feed: /feed

# ref: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:title
