title: 넷평 남짓한 공간

author :
  name : Eunpyoung Kim
  email : netpyoung@gmail.com
  github : netpyoung
  facebook : netpyoung
  feedburner : netpyoung

include: ["blog", "external"]
exclude: ["README.md"]

Paths :
  home: /
  blog: /blog
  external: /external
  resources: /res
  rss : /rss.xml
  atom : /atom.xml

# ref: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:title

pygments: false

markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

  
